FROM cyan/juniper-base

WORKDIR /bp2/src/

EXPOSE 22
EXPOSE 8080

ENV NBI_junipersim_port=22
ENV NBI_easim_port=22
ENV NBI_easim_typeGroup=Juniper
ENV NBI_easim_username=admin
ENV NBI_easim_password=admin
