FROM cyan/rajuniper-base

WORKDIR /bp2/src/

EXPOSE 22
EXPOSE 8080

ENV NBI_rajunipersim_port=22
ENV NBI_rajunipersim_publish=True
ENV NBI_rasim_port=22
ENV NBI_rasim_typeGroup=Juniper
ENV NBI_rasim_username=admin
ENV NBI_rasim_password=admin
ENV NBI_rasim_publish=True
