#!/usr/bin/env python
'''
This is an EXAMPLE hook to connect the sim to eactrl.
'''

import os
import requests
import json
import time
import netifaces

HOOK_SB_INTERFACE_STR = 'BP_HOOK_SOUTHBOUND_INTERFACE'
HOOK_SB_DATA_STR = 'BP_HOOK_SOUTHBOUND_DATA'
EACTRL_STR = 'eactrl'
EACTRL_URL = 'http://{}:{}/api/v1/sessions'
TYPE_GROUP = 'Juniper'
POST_DATA = '{"authentication": {"netconf": {"username": "admin", "password": "admin"}'\
            '}, "connection": '\
            '{"hostname": "%(ip)s", "netconf": {"hostport": %(port)s}'\
            '},'\
            '"typeGroup": "/typeGroups/%(typeGroup)s", "id": "%(_id)s"}'


def get_interface_address(iface='eth0'):
    _if = netifaces.ifaddresses(iface)
    addr = _if[netifaces.AF_INET][0]['addr']
    return addr


print os.environ

if HOOK_SB_INTERFACE_STR in os.environ and HOOK_SB_DATA_STR in os.environ:
    print 'Found valid environ data'

    if os.environ[HOOK_SB_INTERFACE_STR] == EACTRL_STR:
        print 'eactrl interface'

        interface_data = json.loads(os.environ[HOOK_SB_DATA_STR])
        print 'interface_data', interface_data
        self_data = {}
        self_data['ip'] = get_interface_address()
        self_data['_id'] = 'SIM_' + self_data['ip'].replace('.', '')
        self_data['port'] = '22'
        self_data['typeGroup'] = TYPE_GROUP
        print 'self_data', self_data

        if interface_data['state'] == 'up':
            time.sleep(1)
            eactrl_url = EACTRL_URL.format(interface_data['ip'], interface_data['port'])
            print 'state up'
            print 'URL: %s\n<<< %s >>>' % (eactrl_url, POST_DATA % self_data,)
            res = requests.post(
                    eactrl_url,
                    data=POST_DATA % self_data,
                    headers={'Content-Type': 'application/json'})
            print res
        else:
            print 'state down'
            res = requests.delete(
                    eactrl_url + '/%s' % (self_data['_id'],))
            print res
