#!/bin/bash

${DEVICE_RT:-""}

source dockerdev.sh

PRODUCT_ID=$(jcurl ${MARKET_URL}/products?q=resourceTypeId:juniper.resourceTypes.Device | jparse [\"items\"][0][\"id\"])

cat <<EOF > /tmp/resource.json
{
"productId": "${PRODUCT_ID}",
"label": "A Juniper Device",
"discovered": false,
"properties": {
    "typeGroup": "/typeGroups/Juniper",
    "resourceType": "${DEVICE_RT}",
    "authentication": {"netconf": {"username": "admin", "password": "admin"}},
    "connection": {"hostname": "${DEVICE_IP}", "netconf": {"hostport": 22}}
}
}
EOF

jcurl -d @/tmp/resource.json ${MARKET_URL}/resources | jpp

rm -f /tmp/resource.json
