#!/bin/bash

INTERFACE_NAME="ae0.2172"

source dockerdev.sh

PRODUCT_ID=$(jcurl ${MARKET_URL}/products?q=resourceTypeId:juniper.resourceTypes.Interface | jparse [\"items\"][0][\"id\"])
DEVICE_RID=$(jcurl $MARKET_URL/resources?resourceTypeId=juniper.resourceTypes.Device\&label=MX240 | jparse [\"items\"][0][\"id\"])

cat <<EOF > /tmp/resource.json
{
"productId": "${PRODUCT_ID}",
"label": "${INTERFACE_NAME}",
"discovered": false,
"properties": {
    "device": "${DEVICE_RID}",
    "name": "${INTERFACE_NAME}",
    "description": "Ciena test interface - KN",
    "ipv4_addresses": [ "64.191.192.113/28" ],
    "vlan_ids": [ 2172 ]
}
}
EOF

jcurl -d @/tmp/resource.json ${MARKET_URL}/resources | jpp

rm -f /tmp/resource.json
