#!/bin/bash

NAME="AUTOMATE-INET-POC1111"

source dockerdev.sh

PRODUCT_ID=$(jcurl ${MARKET_URL}/products?q=resourceTypeId:juniper.resourceTypes.VlanIdentifier | jparse [\"items\"][0][\"id\"])
DEVICE_RID=$(jcurl $MARKET_URL/resources?resourceTypeId=juniper.resourceTypes.Device\&q=label:QFX5100 | jparse [\"items\"][0][\"id\"])

cat <<EOF > /tmp/resource.json
{
"productId": "${PRODUCT_ID}",
"label": "${NAME}",
"discovered": false,
"properties": {
    "device": "${DEVICE_RID}",
    "name": "${NAME}",
    "vlan_ids": [ 1111 ]
}
}
EOF

jcurl -d @/tmp/resource.json ${MARKET_URL}/resources | jpp

rm -f /tmp/resource.json
