#!/usr/bin/env bash
PORT_MAP=
#PORT_MAP="-p 60000:8080"
CMD="docker run -d $PORT_MAP \
    dockerreg.cyanoptics.com/cyan/rajuniper-sim \
    bpprov-sim rajuniper/model/sim $1 netconf.port=22 --interface=0.0.0.0"
echo $CMD
CID=$($CMD)
echo $CID | cut -c1-12
docker inspect --format '{{ .NetworkSettings.IPAddress }}' ${CID}
